### ISSUE TITLE
Rudimentry ladder

### ISSUE THREAD

**Issue by jegankasi2** [BWRat/DES506_Oneiro#11]
The ladder acts like a trap. Player cannot cancel climbing and must finish the whole action before they can do anything else.

**Comment by Rob1200489** [comment]
To expand upon this bug, the following interactions happen:
- Player can grab the ladder when the player would think they are a safe distance away, snapping the player back onto the ladder
- Player cannot dismount ladder on reaching the bottom, instead they have to detach themselves using another action such as jump.

**Comment by MzxMark** [comment]
About this issue
1. I have adjusted the distance between player and ladder and made it shorter.

**Comment by MzxMark** [comment]
About this issue
2. The bottom of the ladder cannot be embedded in the ground. That should solve this problem.

**Comment by jegankasi2** [comment]
The ladder is no longer a critical A issue

The remaining issue with the ladders are:
1. The player can sometimes snap onto the ladder on the back of the ladder
2. Need more clarification on

**Comment by BWRat** [comment]
@jegankasi2 @MzxMark is this resolved?

**Comment by MzxMark** [comment]
already solved
