### ISSUE TITLE
Player sticks to surfaces 

### ISSUE THREAD

**Issue by Bryanp2408** [BWRat/DES506_Oneiro#13]
- When player jumps into a wall or against anything they temporarily stick to that surface

**Comment by cloneforum** [comment]
It should be fixable applying this physics material to the collider, I am waiting for a confirmation after your test

![image](https://user-images.githubusercontent.com/12499979/61387872-d605f000-a8ae-11e9-9edf-842761a331f1.png)

**Comment by BWRat** [comment]
This was fixed in tandem with #26
