### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by jegankasi2** [BWRat/DES506_Oneiro#15]
The encroaching darkness spawns after the player whenever the player re-spawns at a checkpoint

**Comment by MzxMark** [comment]
this is already solved

**Comment by MzxMark** [comment]
that's already solved

**Comment by BWRat** [comment]
@MzxMark you closed this then reopened it.  Is this resolved?
@jegankasi2 could you also comment whether this is resolved?

**Comment by MzxMark** [comment]
this should be solved, but may need more test about it.
