### ISSUE TITLE
Player can move Multiple times in the Air while Lane Switching

### ISSUE THREAD

**Issue by Bryanp2408** [BWRat/DES506_Oneiro#16]

**Comment by BWRat** [comment]
Move speed on X and Z axes will be separated and made public for ease of designer access and customisation.

**Comment by BWRat** [comment]
Move speed on the two axes was separated by @cloneforum.
@Bryanp2408 please comment to confirm whether or not this issue is resolved.

**Comment by BWRat** [comment]
I've just discussed this with @cloneforum and @jegankasi2, and we've determined that it is not an issue.  Having received no feedback from Bryan about this issue, I am closing it.
@Bryanp2408, if this issue is not actually resolved, please relog it with more detail.
