### ISSUE TITLE
Simplifying controls

### ISSUE THREAD

**Issue by BWRat** [BWRat/DES506_Oneiro#17]
Recommend changes to controls (Designers will handle that part)
(Issue logged on Jegan's behalf after separated from issue #14 )

**Comment by jegankasi2** [comment]
The new control schema:
Left analog --> remains the same
'A' --> Jump
'X' --> To interact with levers 
Change Grab movable objects from 'B' to 'X' as movable objects and Levers are never next to each other
Grow/Shrink Ability changes.
            --> Press 'B' to cycle through all Grow/Shrink object on screen (The player should not be able to cycle through grow/shrink object of-screen)
           --> Press 'Y' to Use players Grow/Shrink Abilities

**Comment by jegankasi2** [comment]
It works now with new controls.
