### ISSUE TITLE
Player movement while holding pushable object

### ISSUE THREAD

**Issue by BWRat** [BWRat/DES506_Oneiro#20]
Related to issue #9 :

If the player holds the right trigger **while approaching** a pushable object, they grab it when it reaches minimum distance, and they can move normally.

If the player walks up against the object **before** pulling the right trigger, they cannot move at all.

This is a movement issue and not an issue with the pushable objects.  This will be remedied by the next iteration of player movement, which @cloneforum is currently reworking.

**Comment by jegankasi2** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48911228/60717719-a227e380-9f1a-11e9-9980-6268e9d7eede.gif)
