### ISSUE TITLE
Description : When the players collider is touching another objects collider and the player is continuously jumping, they are launched in the air

### ISSUE THREAD

**Issue by Bryanp2408** [BWRat/DES506_Oneiro#22]
How many times can you reproduce this bug? Everytime

Steps to Reproduce

Step 1: Walk up to any object so that the players and objects colliders are touching
Step 2: Continue walking forward 
Step 3: While moving forward, continuously Press ‘A’ i.e Jump 
Step 4: Repeat

Additional Information
The heights on the jump vary depending on the height of the object. Tall objects like ladders and walls will only result in the player getting stuck.

![SuperJump](https://user-images.githubusercontent.com/43380465/60723431-85e07280-9f2b-11e9-835e-85ae66535a0f.gif)

**Comment by BWRat** [comment]
@cloneforum, @MzxMark, and I have tested this and determined that it is fixed by the new player controller.
Thanks for the amount of detail in this report. :)
