### ISSUE TITLE
Fatal height

### ISSUE THREAD

**Issue by jegankasi2** [BWRat/DES506_Oneiro#24]
Description
The player need to die and re-spawn when they fall for more than x (x being adjustable) units and then land on the ground. In its current state the death height is set universally in the scene which means the player dies when the player goes down the y-axis instead of dying when the player falls

**Comment by BWRat** [comment]
Although respawning isn't perfect yet, this issue has been actioned.  @jegankasi2 please confirm that fatal height is implemented and working as expected.

**Comment by jegankasi2** [comment]
Yes, It is working as expected
