### ISSUE TITLE
Player on pressure plate

### ISSUE THREAD

**Issue by jegankasi2** [BWRat/DES506_Oneiro#25]
Description
The pressure plate activates the mechanism attached to it when the player steps on it but does not deactivate when the player leaves the pressure plate. The mechanism that got activated remains activated and does not deactivate

 
How many times can you reproduce this bug?
Every time. 

Steps to Reproduce

Move the player onto the pressure plate --> observe mechanism turn on.
Move the player away from the pressure plate --> observe mechanism remain on instead of turning off.

**Comment by BWRat** [comment]
Updated to non-final state.  @jegankasi2 please review the issue.  It is not ready to close, but in its current state I believe it can be lowered to Priority D.

**Comment by jegankasi2** [comment]
The issue has been reviewed. I agree with blake that this issue in its current state can be prioritized lower to D.

**Comment by BWRat** [comment]
Adding an update, as I realise that the description no longer accurately depicts this issue.

The doors now operate mostly as expected with the pressure plates.  Standing on the plate opens the corresponding door, and stepping off closes it.  The functionality is there, but the door will sometimes snap open or closed if the player steps onto or off of the pressure plate too quickly.  See the gif below.

![Door](https://user-images.githubusercontent.com/46999904/61384476-950add00-a8a8-11e9-837d-0c703376f533.gif)
