### ISSUE TITLE
Player getting stuck on edge collision

### ISSUE THREAD

**Issue by jegankasi2** [BWRat/DES506_Oneiro#31]
![1](https://user-images.githubusercontent.com/48911228/61380771-e2378080-a8a1-11e9-9057-9c5041ff09d9.PNG)
When the player jumps onto any elevated platform with a box collider and lands on the very edge, the player stuck. The player cannot move left, right or jump. The only current way to break this player movement lock is to change lanes if there is nothing in the other lane

**Comment by cloneforum** [comment]
problem fixed, apply this physics material to the cap collider
![image](https://user-images.githubusercontent.com/12499979/61387530-38aabc00-a8ae-11e9-88c2-fadaee36bdb2.png)
