### ISSUE TITLE
Play button does not redirect to new scene

### ISSUE THREAD

**Issue by Rob1200489** [BWRat/DES506_Oneiro#33]
Play button does not function in final build. This is most likely because it does not direct to Master scene.

**Comment by Rob1200489** [comment]
Upon further inspection, it seems that the audio manager is also contributing to the bug

**Comment by MzxMark** [comment]
the audio manager in the main menu scene must have level music in the inspector

**Comment by MzxMark** [comment]
![](https://cdn.discordapp.com/attachments/572220492765724674/602466061878820866/unknown.png)

**Comment by MzxMark** [comment]
and type the game scene's name in the main camera's inspector off main menu scene

![](https://cdn.discordapp.com/attachments/572220492765724674/602466751589908500/unknown.png)

![](https://cdn.discordapp.com/attachments/572220492765724674/602466966296461313/unknown.png)

and finally add the game scene into build setting in unity
