### ISSUE TITLE
Multiple objects can be selected at the same time in some instances

### ISSUE THREAD

**Issue by Rob1200489** [BWRat/DES506_Oneiro#36]
In one case in the cave section, the selection of the mushroom is very difficult and when the game does decide to select it, it is selected in addition to the vine.

![Capture](https://user-images.githubusercontent.com/50617758/61590101-86c00800-abab-11e9-84db-62c29248001f.JPG)

**Comment by cloneforum** [comment]
I think it can be closed it isn't happening anymore

**Comment by BWRat** [comment]
This was resolved a while ago but never closed.  Closing now.
