### ISSUE TITLE
Missing collider on walkable surface

### ISSUE THREAD

**Issue by Rob1200489** [BWRat/DES506_Oneiro#37]
Cannot complete game due to missing collider on platform

![Capture](https://user-images.githubusercontent.com/50617758/61590124-c5ee5900-abab-11e9-885a-258cc3f5c1c5.JPG)

Update: More missing colliders

![Capture](https://user-images.githubusercontent.com/50617758/61590166-807e5b80-abac-11e9-805b-34ca6e5b9edb.JPG)

**Comment by Rob1200489** [comment]
I will go through and fix all collisions ready for tomorrow once the current art pass is done

**Comment by BWRat** [comment]
@Rob1200489 tells me this is fixed.  Closing.
