### ISSUE TITLE
Growing Vine cannot be selected

### ISSUE THREAD

**Issue by Rob1200489** [BWRat/DES506_Oneiro#38]
No matter what button is pressed, no matter the position, I cannot interact with this growing vine, causing a block in progress

Scene: The_Master

![Capture](https://user-images.githubusercontent.com/50617758/61593824-74aa8d80-abdc-11e9-8555-a4385fe651bd.JPG)

Also happens here:

![Capture](https://user-images.githubusercontent.com/50617758/61596314-8b131200-abf9-11e9-838b-ad33f1ff5bad.JPG)

**Comment by BWRat** [comment]
This was resolved a while ago but never closed
