### ISSUE TITLE
If the player holds down the lane switch button the animation continues to play

### ISSUE THREAD

**Issue by Bryanp2408** [BWRat/DES506_Oneiro#47]
If the player holds down up or down they  continue to perform the lane switch animation

How frequently can you reproduce this bug? Everytime

Steps to Reproduce

Perform a lane switch 
Hold the analog stick in the UP or DOWN direction

Additional Information

**Comment by BWRat** [comment]
@Bryanp2408 I believe this is fixed.  Please comment to confirm once you have tested it.

**Comment by BWRat** [comment]
Bryan confirmed in person.  Closing the issue.
