### ISSUE TITLE
The Lane switch animation doesn't mirror directions

### ISSUE THREAD

**Issue by Bryanp2408** [BWRat/DES506_Oneiro#48]
Description
When you switch to a new lane the animation does not mirror to the lane you are switching to 

How frequently can you reproduce this bug? Every time 

Steps to Reproduce

Switch a lane

Additional Information

![Switch](https://user-images.githubusercontent.com/43380465/61955666-6c26ce00-afb3-11e9-9877-05351e306669.gif)

**Comment by BWRat** [comment]
Lowered to Priority F because it is completely unnoticeable from the player's perspective, but @Rob1200489 won't let me just close the issue.

**Comment by BWRat** [comment]
This is completely unnoticeable from the player's perspective.
