### ISSUE TITLE
Player can bring object with them when they die

### ISSUE THREAD

**Issue by Bryanp2408** [BWRat/DES506_Oneiro#56]
If the player is holding onto an object i.e a push/pull block and the player dies, both the player and the object will respawn at the check point  

How frequently can you reproduce this bug? Everytime

Steps to Reproduce

Step 1 Grab/Hold onto a push pull block
Step 2 Player has to be switching lane while the dying 
Step 3 Both player and block will respawn together

![PAfG2UZqDH](https://user-images.githubusercontent.com/43380465/62144409-ac56bb00-b2e9-11e9-9898-8ed1f0ff40df.gif)

Additional Information

**Comment by Bryanp2408** [comment]
Yep its fixed.

**Comment by BWRat** [comment]
Bryan has just brought a new version of this bug to my attention.  The initial description is resolved, but if the player is switching lanes when they die, the box is no longer accessible.  Looking into it now.
