### ISSUE TITLE
Push/Pull object on top of mushroom

### ISSUE THREAD

**Issue by jegankasi2** [BWRat/DES506_Oneiro#7]
Push/pull boxes collisions fails on top of a growing mushroom

**Comment by jegankasi2** [comment]
Issue was fixed as other issues were resolved

**Comment by jegankasi2** [comment]
This bug has reappeared. I can recreate this bug every time. A GIF has been attached for reference. I have reopened the issue and assigning the same priority as this bug halts player progress.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/48911228/62043273-db8cff80-b1f7-11e9-8aa1-25efbb3fd6fd.gif)

**Comment by cloneforum** [comment]
problem fixed, move this script from here
![image](https://user-images.githubusercontent.com/12499979/62295587-4c851f00-b465-11e9-93b8-d385b4617594.png)

to here

![image](https://user-images.githubusercontent.com/12499979/62295614-5c046800-b465-11e9-8a6d-79ef761a83c7.png)


I am waiting for approval to close

**Comment by BWRat** [comment]
@jegankasi2 has confirmed that this is fixed
