### ISSUE TITLE
 The player doesn’t change direction

### ISSUE THREAD

**Issue by Bryanp2408** [BWRat/DES506_Oneiro#8]
When you move to the left they face left, when you move to the right player still faces left.

**Comment by BWRat** [comment]
Implemented a fix for this at 11:17am on 04.07.2019.  @Bryanp2408 or another designer, please post a comment confirming this is fixed.

**Comment by BWRat** [comment]
Note: Bryan is absent today, I am absent tomorrow, and this issue must be closed before the end of the week.  @jegankasi2 please comment to confirm whether or not this is fixed.

**Comment by jegankasi2** [comment]
Player ability to change direction has been tested after implementation. It works.
